name: method_channel
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  image: ^3.1.3
  http: ^0.13.4
  archive: ^3.3.1
  path_parsing: ^1.0.0
  plugin_platform_interface: ^2.1.2
  ffi: ^1.2.1
  js: ^0.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true